// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package sqlcgen

import (
	"context"
)

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (post_id, author_id)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE post_id = post_id
`

type CreateLikeParams struct {
	PostID   []byte
	AuthorID []byte
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.ExecContext(ctx, createLike, arg.PostID, arg.AuthorID)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE post_id = ? AND author_id = ?
`

type DeleteLikeParams struct {
	PostID   []byte
	AuthorID []byte
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteLike, arg.PostID, arg.AuthorID)
	return err
}
