// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Like struct {
	PostID    []byte
	AuthorID  []byte
	CreatedAt time.Time
}

type Post struct {
	ID        []byte
	TopicID   []byte
	AuthorID  []byte
	Body      string
	CreatedAt time.Time
	Title     string
}

type Session struct {
	ID        string
	UserID    []byte
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Topic struct {
	ID           []byte
	Slug         string
	Name         string
	DisplayOrder int32
}

type User struct {
	ID           []byte
	DisplayName  string
	CreatedAt    time.Time
	Email        string
	PasswordHash string
}
