// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Like struct {
	PostID    pgtype.UUID
	AuthorID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID        pgtype.UUID
	TopicID   pgtype.UUID
	AuthorID  pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type Topic struct {
	ID           pgtype.UUID
	Slug         string
	Name         string
	DisplayOrder int32
}

type User struct {
	ID          pgtype.UUID
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}
