// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	UserID    []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
  s.id AS session_id,
  s.expires_at AS expires_at,
  u.id AS user_id,
  u.display_name AS display_name,
  u.email AS email
FROM sessions s
JOIN users u ON s.id = u.id
WHERE s.id = ?
AND s.expires_at > ?
`

type GetSessionWithUserParams struct {
	ID  string
	Now time.Time
}

type GetSessionWithUserRow struct {
	SessionID   string
	ExpiresAt   time.Time
	UserID      []byte
	DisplayName string
	Email       string
}

func (q *Queries) GetSessionWithUser(ctx context.Context, arg GetSessionWithUserParams) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, arg.ID, arg.Now)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}
