// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package sqlcgen

import (
	"context"
)

const getTopicBySlug = `-- name: GetTopicBySlug :one
SELECT id, slug, name, display_order
FROM topics
WHERE slug = ?
`

func (q *Queries) GetTopicBySlug(ctx context.Context, slug string) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopicBySlug, slug)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayOrder,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT id, slug, name, display_order
FROM topics
ORDER BY display_order ASC, slug ASC
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
