// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, display_name, email, password_hash)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           []byte
	DisplayName  string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, display_name, created_at, email, password_hash
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
SET display_name = ?
WHERE id = ?
`

type UpdateUserDisplayNameParams struct {
	DisplayName string
	ID          []byte
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}
